[package]
name = "libp2p-rendezvous"
edition = "2018"
description = "Rendezvous protocol for libp2p"
version = "0.1.0"
authors = ["Comit Guys <hello@comit.network>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
libp2p-core = { version = "0.28.0", path = "../../core" }
libp2p-swarm = { version = "0.29.0", path = "../../swarm" }
prost = "0.7"


[build-dependencies]
prost-build = "0.7"
