[package]
name = "libp2p-rendezvous"
edition = "2018"
description = "Rendezvous protocol for libp2p"
version = "0.1.0"
authors = ["Comit Guys <hello@comit.network>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
asynchronous-codec = "0.6"
libp2p-core = { version = "0.28.0", path = "../../core" }
libp2p-swarm = { version = "0.29.0", path = "../../swarm" }
prost = "0.7"
void = "1"
log = "0.4"
futures = { version = "0.3", default-features = false, features = ["std"] }
thiserror = "1" # TODO: REMOVE FOR PRODUCTION USE
unsigned-varint = { version = "0.7", features = ["asynchronous_codec"] }
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
libp2p-tcp = { path = "../../transports/tcp" }
libp2p-noise = { path = "../../transports/noise" }
libp2p-yamux = { path = "../../muxers/yamux" }
libp2p-mplex = { path = "../../muxers/mplex" }
rand = "0.8"
async-std = "1.6.2"
env_logger = "0.8"
tokio = { version = "1", features = [ "rt-multi-thread", "time", "macros", "sync", "process", "fs", "net" ] }
async-trait = "0.1"

[build-dependencies]
prost-build = "0.7"
